name: CD - Production

on:
  push:
    tags:
      - v**


jobs:
  staging-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          python -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install -r pointing_poker/aws/requirements.txt
          pip install -r pointing_poker/aws/resources/requirements.txt

      - name: Configure AWS Credentials for Production Deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to Production
        run: |
          source venv/bin/activate
          cdk bootstrap
          cdk deploy --require-approval=never

      - name: Run Acceptance Tests
        run: |
          source venv/bin/activate
          export GRAPHQL_API_ID=$(aws appsync list-graphql-apis | jq ".graphqlApis[0].apiId" | sed 's/\"//g')
          export GRAPHQL_ENDPOINT=$(aws appsync list-graphql-apis | jq ".graphqlApis[0].uris.GRAPHQL" | sed 's/https:\/\///' | sed 's/\/graphql//' | sed 's/"//g')
          NOW=$(date +%s)
          export API_KEY_EXPIRATION=$(($NOW + (2 * 24 * 60 * 60)))
          export API_KEY=$(aws appsync create-api-key --api-id $GRAPHQL_API_ID --expires $API_KEY_EXPIRATION | jq ".apiKey.id" | sed 's/"//g')
          behave

